server:
  port: 8084

spring:
  application:
    name: logging-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vbank_db
    username: postgres
    password: Mm2264764
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: logging_schema
        javax.persistence.schema-generation.database.action: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: logging-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer